name: Linux Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
    contents: write

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/Reusable_Workflow.yml
    with:
      os: Linux
      name: Linux_Release
      pretty_name: Linux Release
      python_path: .venv/bin/python
      conan_install_step_name: "conan_install_linux_gcc_release"
      build_project_files_step_name: "build_project_release_ninja"
      compile_step_name: "compile_project_release"
