name: Linux Debug

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
    contents: write

jobs:
  print_debug_info:
    runs-on: self-hosted
    steps:
      - name: Print important env vars
        run: printenv XDG_RUNTIME_DIR && ls -ld "$XDG_RUNTIME_DIR"
        
  call_reusable_workflow:
    uses: ./.github/workflows/Reusable_Workflow.yml
    with:
      os: Linux
      name: Linux_Debug
      pretty_name: Linux Debug
      python_path: .venv/bin/python
      conan_install_step_name: "conan_install_linux_gcc_debug"
      build_project_files_step_name: "build_project_debug_ninja"
      compile_step_name: "compile_project_debug"
