name: Linux Debug

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
    contents: write

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/reusable_workflow.yml
    with:
      os: Linux
      name: Linux_Debug
      pretty_name: Linux Debug
      python_path: .venv/bin/python
      conan_install_step_name: "conan_install_linux_gcc_debug"
      build_project_files_step_name: "build_project_debug_ninja"
      compile_step_name: "compile_project_debug"
