name: Reusable Workflow

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      pretty_name:
        required: true
        type: string
      name:
        required: true
        type: string
      python_path:
        required: true
        type: string
      conan_install_step_name:
        required: true
        type: string
      build_project_files_step_name:
        required: true
        type: string
      compile_step_name:
        required: true
        type: string
      
jobs:
  linux_debug_info:
    runs-on: Linux
    steps:
      - name: Print important env vars
        run: printenv XDG_RUNTIME_DIR && ls -ld "$XDG_RUNTIME_DIR"
    
  build_test_deploy_upload:
    runs-on: 
      - ${{ inputs.os }}
      - self-hosted
    name: ${{ inputs.name }}

    steps:
      - uses: actions/checkout@v4

      - name: Debug Info
        run: echo "Runner name ${{ runner.name }}"

      - name: Setup Project
        run: python3 first_time.py

      - name: Pytest Tools
        run: ${{ inputs.python_path }} -m pytest Tools/tests

      - name: Generate Project Files AddressSanitizer Off
        run: ${{ inputs.python_path }} menu.py --OptionName generate_project_address_sanitizer_off

      - name: Conan Install
        run: ${{ inputs.python_path }} menu.py --OptionName ${{ inputs.conan_install_step_name }}

      - name: Build Project Files
        run: ${{ inputs.python_path }} menu.py --OptionName ${{ inputs.build_project_files_step_name }}

      - name: Compile project
        run: ${{ inputs.python_path }} menu.py --OptionName ${{ inputs.compile_step_name }}

      - name: Run All Automatic Tests
        run: ${{ inputs.python_path }} menu.py --OptionName run_all_automatic_tests
