name: Ubuntu Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
    contents: write

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/reusable_workflow.yml
    with:
      os: ubuntu-latest
      name: Ubuntu_Latest
      pretty_name: Ubuntu Latest
      python_path: .venv/bin/python
      conan_install_step_name: "conan_install_linux_gcc_release"
      build_project_files_step_name: "build_project_release_ninja"
      compile_step_name: "compile_project_release"