name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
    contents: write

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/reusable_workflow.yml
    with:
      os: ubuntu-latest
      name: Ubuntu_Latest
      pretty_name: Ubuntu Latest
      python_path: .venv/bin/python