name: Windows Release

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

permissions:
    contents: write

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/Reusable_Workflow.yml
    with:
      os: windows
      name: Windows_Release
      pretty_name: "Windows Release"
      python_path: ".venv/Scripts/python.exe"
      conan_install_step_name: "conan_install_windows_msvc_release"
      build_project_files_step_name: "build_project_release_visual_studio"
      compile_step_name: "compile_project_release"
