name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
    contents: write

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/reusable_workflow.yml
    with:
      os: windows
      name: Windows_Debug
      pretty_name: "Windows Debug"
      python_path: .venv/Scripts/python.exe
      conan_install_step_name: "conan_install_windows_msvc_debug"
      build_project_files_step_name: "build_project_debug_visual_studio"
      compile_step_name: "compile_project_debug"
